#directory: '/home/arvc/Escritorio/develop/Registration/dos_vueltas_features/'
directory: '/media/arvc/INTENSO/DATASETS/dos_vueltas_long_range'

down_sample:
  voxel_size: 0.03 # Number or None

filter_by_distance:
  decision: true
  distance: 35

filter_ground_plane:
  decision: true
  radius_normals: 3
  maximum_neighbors: 200

normals:
  maximum_neighbors: 50
  radius_normals: 0.5

icp:
  point2: 'plane'
  distance_threshold: 7
  step: 5

visualization:
  normals: false
  registration_result: false

experiment:
  deltaxy: 0.1
  deltath: 0.05
  long: 600
